import {
	Candlestick,
	Category,
	ConnectionType,
	SignalRisk,
	SignalStatus,
	TradeSide,
	TradeType,
} from "../config/enums";

export const exchangeData = {
	_id: 270,
	name: "Binance",
	slug: "binance",
	logo: "binance.png",
	description: "Binance exchange",
	status: "ACTIVE",
	urls: "https://binance.com",
	makerFee: 0.1,
	takerFee: 0.1,
	dateLaunched: new Date(),
	category: [Category.CRYPTO],
	connectionTypes: [ConnectionType.MANUAL],
	isIpAddressWhitelistRequired: true,
	isSpotTradingSupported: true,
	isFuturesTradingSupported: true,
	isMarginTradingSupported: true,
};

export const quoteCurrencyData = {
	_id: 825,
	name: "Tether USDT",
	symbol: "USDT",
	isTradingActive: true,
	logo: "usdt.png",
};

export const bitcoinCoinData = {
	_id: 1,
	name: "Bitcoin",
	slug: "bitcoin",
	symbol: "BTC",
	logo: "btc.png",
	description: "Bitcoin asset",
	urls: "https://bitcoin.org",
	rank: 1,
	isCoinActive: true,
	isTradingActive: true,
	dateLaunched: new Date(),
	category: Category.CRYPTO,
};

export const cadanoCoinData = {
	_id: 2010,
	name: "Cadano",
	slug: "cadano",
	symbol: "ADA",
	logo: "ada.png",
	description: "Cadano asset",
	urls: "https://cadano.org",
	rank: 11,
	isCoinActive: true,
	isTradingActive: true,
	dateLaunched: new Date(),
	category: Category.CRYPTO,
};

// Signal Data
export const bitcoinSignalData = {
	targetProfits: [
		{ price: 45000, percent: 0, isReached: false },
		{ price: 50000, percent: 0, isReached: false },
		{ price: 55000, percent: 0, isReached: false },
		{ price: 60000, percent: 0, isReached: false },
	],
	stopLoss: { price: 35000, percent: 0, isReached: false },
	entryPrice: 40000,
	entryPriceLowerBound: 39500,
	entryPriceUpperBound: 40500,
	tradeNote: "Bitcoin Test signal",
	candlestick: Candlestick.oneHour,
	risk: SignalRisk.medium,
	isSignalTradable: false,
	isSignalTriggered: false,
	chartUrl: "https://chart.com",
	status: SignalStatus.PENDING,
	maxGain: 0,
	createdAt: new Date().toISOString(),
	supportedTradingPlatform: [exchangeData._id],
	baseAsset: bitcoinCoinData._id,
	baseAssetName: bitcoinCoinData.symbol,
	quoteCurrency: quoteCurrencyData._id,
	quoteCurrencyName: quoteCurrencyData.symbol,
	category: Category.CRYPTO,
	tradeType: TradeType.FUTURES,
	tradeSide: TradeSide.LONG,
	leverage: 4,
};
export const cadanoSignalData = {
	targetProfits: [
		{ price: 0.775, percent: 0, isReached: false },
		{ price: 0.765, percent: 0, isReached: false },
		{ price: 0.76, percent: 0, isReached: false },
		{ price: 0.755, percent: 0, isReached: false },
	],
	stopLoss: { price: 0.8, percent: 0, isReached: false },
	entryPrice: 0.785,
	entryPriceLowerBound: 0.79,
	entryPriceUpperBound: 0.78,
	tradeNote: "Cadano Test signal",
	candlestick: Candlestick.oneHour,
	risk: SignalRisk.medium,
	isSignalTradable: false,
	isSignalTriggered: false,
	chartUrl: "https://chart.com",
	status: SignalStatus.PENDING,
	maxGain: 0,
	createdAt: new Date().toISOString(),
	supportedTradingPlatform: [exchangeData._id],
	baseAsset: cadanoCoinData._id,
	baseAssetName: cadanoCoinData.symbol,
	quoteCurrency: quoteCurrencyData._id,
	quoteCurrencyName: quoteCurrencyData.symbol,
	category: Category.CRYPTO,
	tradeType: TradeType.FUTURES,
	tradeSide: TradeSide.SHORT,
	leverage: 2,
};
