# docker_compose= """
# version: '2.4'
# services:
#   streamlit:
#     build:
#       dockerfile: ./Dockerfile
#       context: ./
#     ports:
#       - '8501:8501'
#     volumes:
#       - /home/jovyan/shared/:/home/jovyan/shared/
#     labels:
#       traefik.http.services.streamlit.loadbalancer.server.port: 8501
#       traefik.http.routers.streamlit.rule: PathPrefix(`/private/streamlit`)
# """
